trigger:
 - main

pool:
   vmImage: 'ubuntu-latest' 

variables:
   imageName: 'pipelines-javascript-docker'

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile
 - task: PythonScript@0
   inputs:
    scriptSource: 'filePath'
    scriptPath: 'scripts/pull_docker_images_2.py'
    workingDirectory: '$(Build.SourcesDirectory)/scripts'
    failOnStderr: true